Reject empty password and "test" for the webinterface.
SpectrumIM/spectrum2 pull request #459
Opened 2022-11-29 15:51 UTC by coldtobi

Well, this is aimed to protect the unaware or the dontcare for inadvertently opening up their spectrum2 webinterface to the world, creating all sorts of security issues on the way…

(I'm using this patch for the Debian package for a hardened default setup; when the user installs the webinterface package, this will automatically also start it, so this is needed for an secure user experience…)

2022-11-29 15:59 UTC, vitalyster commented
This will break Docker Compose example, as it uses different config copy - https://github.com/SpectrumIM/spectrum2/tree/master/tests/xmpp/configuration

2022-11-29 17:31 UTC, vitalyster approved these changes

2022-11-29 18:46 UTC, vitalyster commented
Also I like the approach when secure password is generated on startup and printed to console, maybe better to generate new password instead of error exit?

2022-12-02 03:10 UTC, vitalyster requested changes
Also I like the approach when secure password is generated on startup and printed to console, maybe better to generate new password instead of error exit?

2022-12-02 14:21 UTC, coldtobi commented
@vitalyster commited an proposal for a random password generation.

2022-12-02 14:23 UTC, vitalyster approved these changes

2022-12-02 16:21 UTC, merged